## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/monarch-initiative for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script:
  - make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

### Add your own lists here
### See https://github.com/INCATools/ontology-development-kit/issues/35
notifications:
  email:
    recipients:
      - daniel.c.berrios@nasa.gov
    on_failure: always